### ISSUE TITLE
作る物案

### ISSUE THREAD

**Issue by kouheinishino** [kouheinishino/got-em-snkrs#1]

**Comment by ymmdayo** [comment]
卒業制作について

・要件

1. 画面
2. データベース
3. Aws hirolku
4. PC スマホ
5. テストコード
6. 自動化マスターマージ
7. GitHub

1. スニーカー
2. アイドル
3. コンカフェ
4. シュプリーム
5. アーカイブ

**Comment by ymmdayo** [comment]
アーカイブからの展開？
・アパレル
・カフェ
・トイレ

**Comment by kouheinishino** [comment]
有力候補
ブランドに特化したアパレルアーカイブサイト

**Comment by ymmdayo** [comment]
ログインしてユーザーがアーカイブの更新できるみたいな
・ウィキペディアみたいに
アーカイブの商品についてのコメント（投稿）とか

**Comment by alalain0n** [comment]
### 必須課題
DBから出し入れする
AWSをつかう
PCとスマホ両方で見られるように

**Comment by alalain0n** [comment]
シュプリームのアーカイブ検索サービス

**Comment by alalain0n** [comment]
### 欲しい機能
過去の商品を検索できる
検索するとリンクが貼られる(メルカリ・ラクマ・ヤフオク)
発売日
定価
現在の相場
ジャンル(Tシャツ・帽子等)
絞り込みをできるようにする

**Comment by alalain0n** [comment]
### やることリスト
